name: "Lagoss CLI"
description: "Easily integrate Lagoss CLI operations into your Github workflow"
branding:
  icon: code
  color: blue
inputs:
  lagoss_token:
    description: "Your Lagoss API token"
    required: true
  command:
    description: 'The Lagoss CLI command to run. For example: "deploy" - will publish your application'
    required: false
    default: "deploy --prod"
  site_url:
    description: "Specify custom url for self-hosted Lagoss instances"
    required: false
    default: "https://console.lagoss.com"
  config:
    description: "Pass in .lagoss/config.json file for your application"
    required: false
    default: ""
outputs:
  cli_stdout:
    description: "The raw stdout from the CLI command executed"
    value: ${{ steps.cli.outputs.cli_stdout }}
runs:
  using: "composite"
  steps:
    - name: "Install Node.js"
      uses: actions/setup-node@v3
      with:
        node-version: 24

    - name: "Install CLI"
      shell: bash
      run: |
        npm install --global @lagoss/cli esbuild

    - name: "Execute CLI"
      id: cli
      env:
        LAGOSS_TOKEN: ${{ inputs.lagoss_token }}
        LAGOSS_COMMAND: ${{ inputs.command }}
        LAGOSS_URL: ${{ inputs.site_url }}
        LAGOSS_CONFIG: ${{ inputs.config }}
      shell: bash
      run: |
        echo "Configuring lagoss CLI..."
        if [[ -z "${LAGOSS_TOKEN}" ]]; then
            echo "LAGOSS_TOKEN input is not set"
            exit 1
        fi

        # Setup config folders
        mkdir -p "$HOME/.lagoss"

        # Setup auth
        echo \{\"token\":\""${LAGOSS_TOKEN}"\",\"site_url\":\""${LAGOSS_URL}"\"\} | jq >"$HOME/.lagoss/config.json"

        # Setup lagoss function config if one was provided
        if [[ -n "${LAGOSS_CONFIG}" ]]; then
            echo "LAGOSS_CONFIG variable set from environment. Applying config ..."
            mkdir -p .lagoss
            echo "$LAGOSS_CONFIG" | jq >.lagoss/config.json
        fi

        # Run CLI
        echo "Executing CLI ..."
        eval "lagoss $LAGOSS_COMMAND" | tee lagoss.output
        # Action is done!
        exit $?
